# Generated by Django 3.2 on 2024-08-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_english', models.CharField(max_length=20, unique=True)),
                ('in_persian', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tags', models.ManyToManyField(related_name='posts_of', to='news_api.Tag')),
            ],
        ),
    ]
